// ======= DO NOT EDIT THIS FILE ============
class Node {
  Rabbit info;
  Node next;
  Node() {
   }
  Node(Rabbit x, Node p) {
    info=x;next=p;
   }
  Node(Rabbit x) {
    this(x,null);
   }
 }

