// ======= DO NOT EDIT THIS FILE ============
class Rabbit {
  String forest;
  int food,rate;
  Rabbit() {
   }
  Rabbit(String xForest, int xFood, int xRate){
    forest=xForest;food=xFood; rate=xRate;
   }
  public String toString(){
    return("(" +forest+","+food + "," + rate + ")");
   }
 }
